"""empty message

Revision ID: 061b4e7eccee
Revises: d110423ffb4a
Create Date: 2023-12-14 14:59:10.133263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061b4e7eccee'
down_revision = 'd110423ffb4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverydetail', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key("asdfasdf", 'deliverydetail', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("asdfasdf", 'deliverydetail', type_='foreignkey')
    op.drop_column('deliverydetail', 'customer_id')
    # ### end Alembic commands ###
