"""empty message

Revision ID: 3416aadc9a11
Revises: 0fd05de6fe6f
Create Date: 2023-12-14 23:04:30.872690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3416aadc9a11'
down_revision = '0fd05de6fe6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'basket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'basket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
