"""empty message

Revision ID: f23f88f26bff
Revises: 2bc0040dd3ae
Create Date: 2023-12-11 09:39:58.631266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23f88f26bff'
down_revision = '2bc0040dd3ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('data_created', sa.DateTime(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalogitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('catalogitem', 'item_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogitem', 'item_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('product')
    # ### end Alembic commands ###
